### ISSUE TITLE
oxford radar dataset h5 file

### ISSUE THREAD

**Issue by jinxxo-j** [raktimgg/FlashMix#1]
Hello! thank you for your interesting works
I have a question about your works.

In Readme, I saw the message below and checked the pre-generated file, but it doesn’t download. I would appreciate it if you could fix this!

velodyne_left_False.h5 files can be generated using the data generator in [PosePN](https://github.com/PSYZ1234/PosePN). Alternately, we provide the pre-generated file [here](https://github.com/raktimgg/FlashMix/blob/main).

**Comment by raktimgg** [comment]
Hi, we have updated the download link. You should now be able to download the velodyne_left_False.h5 files.

**Comment by jinxxo-j** [comment]
Thank you!
